FROM alpine:3.9
LABEL maintainer="chenxuefeng<chenxuefeng1@guazi.com"

# build openresty
ARG RESTY_IMAGE_BASE="alpine"
ARG RESTY_IMAGE_TAG="3.9"
ARG RESTY_VERSION="1.13.6.2"
ARG RESTY_OPENSSL_VERSION="1.1.1b"
ARG KONG_OPENSSL_VESION="1.1.1b-r1"
ARG RESTY_PCRE_VERSION="8.42"
ARG RESTY_J="1"
ARG RESTY_CONFIG_OPTIONS="\
    --with-file-aio \
    --with-http_addition_module \
    --with-http_auth_request_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_geoip_module=dynamic \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_image_filter_module=dynamic \
    --with-http_mp4_module \
    --with-http_random_index_module \
    --with-http_realip_module \
    --with-http_secure_link_module \
    --with-http_slice_module \
    --with-http_ssl_module \
    --with-http_stub_status_module \
    --with-http_sub_module \
    --with-http_v2_module \
    --with-http_xslt_module=dynamic \
    --with-ipv6 \
    --with-mail \
    --with-mail_ssl_module \
    --with-md5-asm \
    --with-pcre-jit \
    --with-sha1-asm \
    --with-stream \
    --with-stream_ssl_module \
    --with-threads \
    "
ARG RESTY_CONFIG_OPTIONS_MORE=""
ARG RESTY_ADD_PACKAGE_BUILDDEPS=""
ARG RESTY_ADD_PACKAGE_RUNDEPS=""
ARG RESTY_EVAL_PRE_CONFIGURE=""
ARG RESTY_EVAL_POST_MAKE=""
ARG RESTY_LUAROCKS_VERSION="3.1.3"
ARG KONG_VERSION="1.2.1"
ARG KONG_URL=https://github.com/Kong/kong/archive/${KONG_VERSION}.tar.gz

LABEL resty_image_base="${RESTY_IMAGE_BASE}"
LABEL resty_image_tag="${RESTY_IMAGE_TAG}"
LABEL resty_version="${RESTY_VERSION}"
LABEL resty_openssl_version="${RESTY_OPENSSL_VERSION}"
LABEL resty_pcre_version="${RESTY_PCRE_VERSION}"
LABEL resty_config_options="${RESTY_CONFIG_OPTIONS}"
LABEL resty_config_options_more="${RESTY_CONFIG_OPTIONS_MORE}"
LABEL resty_add_package_builddeps="${RESTY_ADD_PACKAGE_BUILDDEPS}"
LABEL resty_add_package_rundeps="${RESTY_ADD_PACKAGE_RUNDEPS}"
LABEL resty_eval_pre_configure="${RESTY_EVAL_PRE_CONFIGURE}"
LABEL resty_eval_post_make="${RESTY_EVAL_POST_MAKE}"

ARG _RESTY_CONFIG_DEPS="--with-openssl=/tmp/openssl-${RESTY_OPENSSL_VERSION}  --with-pcre=/tmp/pcre-${RESTY_PCRE_VERSION}"

ARG OPENRESTY_PATCHS_URL=https://github.com/Kong/openresty-patches/archive/master.tar.gz


ENV PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin 

ADD kong /usr/local/bin/
ADD docker-entrypoint.sh /


RUN apk update && apk  add --no-cache --virtual .build-deps \
        build-base coreutils curl git \
        gd-dev geoip-dev libxslt-dev linux-headers \
        make perl-dev readline-dev zlib-dev \
        ${RESTY_ADD_PACKAGE_BUILDDEPS} gd geoip libgcc \
        libxslt zlib ${RESTY_ADD_PACKAGE_RUNDEPS}  bash \
        outils-md5 perl unzip openssl-dev=${KONG_OPENSSL_VESION} \
        bsd-compat-headers m4 yaml-dev \ 
        tzdata su-exec \
    && cd /tmp \
    && if [ -n "${RESTY_EVAL_PRE_CONFIGURE}" ]; then eval $(echo ${RESTY_EVAL_PRE_CONFIGURE}); fi \
    && curl -fSL https://www.openssl.org/source/openssl-${RESTY_OPENSSL_VERSION}.tar.gz -o openssl-${RESTY_OPENSSL_VERSION}.tar.gz \
    && tar xzf openssl-${RESTY_OPENSSL_VERSION}.tar.gz  \
    && curl -fSL https://ftp.pcre.org/pub/pcre/pcre-${RESTY_PCRE_VERSION}.tar.gz -o pcre-${RESTY_PCRE_VERSION}.tar.gz \
    && tar xzf pcre-${RESTY_PCRE_VERSION}.tar.gz \
    && curl -fSL https://openresty.org/download/openresty-${RESTY_VERSION}.tar.gz -o openresty-${RESTY_VERSION}.tar.gz \
    && tar xzf openresty-${RESTY_VERSION}.tar.gz \
   # && if [[ "1.1.1" == $(echo -e "${RESTY_OPENSSL_VERSION}\n1.1.1" | sort -V | head -n1) ]] ; then \
    #    echo 'patching Nginx for OpenSSL 1.1.1' \
    #    && cd bundle/nginx-1.13.6 \
    #    && curl -s https://raw.githubusercontent.com/openresty/openresty/master/patches/nginx-1.13.6-ssl_cert_cb_yield.patch | patch -p1 \
    #    && curl -s https://raw.githubusercontent.com/openresty/openresty/master/patches/nginx-1.13.6-ssl_sess_cb_yield.patch | patch -p1 \
    #    && cd ../.. ; \
    #fi \
    && wget -c "${OPENRESTY_PATCHS_URL}" -O -| tar -C /tmp -zx  \
    && cd "/tmp/openresty-${RESTY_VERSION}"/bundle/ \
    && for i in /tmp/openresty-patches-master/patches/${RESTY_VERSION}/*.patch; do patch -p1 < $i; done \
    && cd "/tmp/openresty-${RESTY_VERSION}" \
    && ./configure -j${RESTY_J} ${_RESTY_CONFIG_DEPS} ${RESTY_CONFIG_OPTIONS} ${RESTY_CONFIG_OPTIONS_MORE} \
    && make -j${RESTY_J} \
    && make -j${RESTY_J} install \
    && cd /tmp \
    && if [ -n "${RESTY_EVAL_POST_MAKE}" ]; then eval $(echo ${RESTY_EVAL_POST_MAKE}); fi \
    && cd /tmp \
    && curl -fSL https://luarocks.github.io/luarocks/releases/luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz -o luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
    && tar xzf luarocks-${RESTY_LUAROCKS_VERSION}.tar.gz \
    && cd luarocks-${RESTY_LUAROCKS_VERSION} \
    && ./configure \
        --prefix=/usr/local/openresty/luajit \
        --with-lua=/usr/local/openresty/luajit \
        --lua-suffix=jit \
        --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1 \
    && make build && make install \
    && cd /tmp \
    && apk add --no-cache --virtual .gettext gettext \
    && mv /usr/bin/envsubst /tmp/ \
    && runDeps="$( \
        scanelf --needed --nobanner /tmp/envsubst \
            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
            | sort -u \
            | xargs -r apk info --installed \
            | sort -u \
    )" \
    && apk add --no-cache --virtual $runDeps \
    && mv /tmp/envsubst /usr/local/bin/ \
    && wget  -c "${KONG_URL}" -O -| tar -C /tmp -zx  \
    && cd /tmp/kong-${KONG_VERSION} && make install  &&  cd /tmp \
    && adduser -Su 1337 kong \ 
    && ln -s /usr/share/zoneinfo/Etc/GMT-8 /etc/localtime \
    && echo "Asia/Shanghai" >  /etc/timezone \
    && mkdir -p /usr/local/kong \
    && chmod +x /docker-entrypoint.sh  \
    && chmod +x /usr/local/bin/kong \
    && cd /tmp && rm -rf * \ 
    && apk del .build-deps build-base make gcc git  wget  patch  unzip .gettext tzdata

EXPOSE 8000 8443 8001 8444

STOPSIGNAL SIGTERM

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["kong", "docker-start"]


  
